<a href="https://colab.research.google.com/github/shubhaankargupta/blueddddd/blob/main/ACM_Week_2_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Processing Images

In [1]:
!wget https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/640px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg

--2024-01-31 22:43:31--  https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/640px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg
Resolving upload.wikimedia.org (upload.wikimedia.org)... 198.35.26.112, 2620:0:863:ed1a::2:b
Connecting to upload.wikimedia.org (upload.wikimedia.org)|198.35.26.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 202433 (198K) [image/jpeg]
Saving to: ‘640px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg’

640px-Mona_Lisa,_by 100%[===================>] 197.69K  --.-KB/s    in 0.06s   

2024-01-31 22:43:31 (3.18 MB/s) - ‘640px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg’ saved [202433/202433]




You may want to run
```
!pip install PIL
```



In [25]:
from matplotlib import pyplot as plt
from numpy import asarray
from PIL import Image

image = Image.open('/content/640px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg')
matrix = asarray(image)
print(matrix)

[[[104 116  92]
  [ 82  94  70]
  [107 119  99]
  ...
  [ 93  97  83]
  [114 115 107]
  [ 92  92  84]]

 [[115 127 103]
  [ 97 109  85]
  [ 96 108  86]
  ...
  [ 86  90  76]
  [ 83  85  74]
  [ 72  72  62]]

 [[ 90 103  77]
  [ 87  99  75]
  [ 94 106  84]
  ...
  [ 79  86  68]
  [ 62  64  51]
  [ 38  38  26]]

 ...

 [[118 112 126]
  [ 82  75  91]
  [ 46  38  59]
  ...
  [ 36  32  47]
  [140 134 148]
  [ 40  34  46]]

 [[129 123 135]
  [ 49  43  57]
  [109 102 120]
  ...
  [ 33  26  42]
  [ 72  64  79]
  [ 35  27  42]]

 [[119 113 125]
  [ 48  42  56]
  [ 77  70  88]
  ...
  [117 110 126]
  [ 37  29  44]
  [101  93 108]]]


In [27]:
bw = image.convert('L')
matrix_bw = asarray(bw)
print(matrix_bw)

[[110  88 113 ...  94 114  91]
 [121 103 102 ...  87  83  71]
 [ 96  93 100 ...  82  62  37]
 ...
 [115  79  43 ...  35 137  37]
 [126  46 106 ...  30  68  31]
 [116  45  74 ... 114  33  97]]


In [30]:
print(matrix[0][1])
print(matrix_bw[0][1])

[82 94 70]
88


In [31]:
bw = bw.save('bw.png')